title: '&cДОСТУП К МИРУ ЗАКРЫТ'
subtitle: '&fПодписка не оформлена'

chat_msg:
  - ' '
  - '   &cДЛЯ ДОСТУПА К ЗАКРЫТОМУ МИРУ'
  - '      &cТРЕБУЕТСЯ ПОДПИСКА'
  - ' '
  - '   &7КУПИТЬ ПОДПИСКУ ЗДЕСЬ:'
  - '   &6https://mcadventure.net'
  - '   &c(СКИДКА) &f+ VIP В ПОДАРОК'
  - ' '